name: Sync JSON File

on:
  workflow_dispatch:
  push:
    branches:
      - main  # 或者您的默认分支名
  schedule:
    - cron: '*/1 * * * *'  # 每分钟执行一次

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Download JSON File
      run: curl -o data.json https://data-v2.hacs.xyz/integration/data.json

    - name: Commit and Push
      run: |
        git config --global user.email "youremail@example.com"
        git config --global user.name "Your Name"
        git add data.json
        git commit --allow-empty -m "Update data.json"  # 即使没有变动也创建提交
        git push
